// auth
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD_ENTRY =
  'SIGN_UP_WITH_EMAIL_AND_PASSWORD_ENTRY';
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD_SUCCESS =
  'SIGN_UP_WITH_EMAIL_AND_PASSWORD_SUCCESS';
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD_FAILED =
  'SIGN_UP_WITH_EMAIL_AND_PASSWORD_FAILED';
export const SIGN_UP_WITH_EMAIL_AND_PASSWORD_RECOVER =
  'SIGN_UP_WITH_EMAIL_AND_PASSWORD_RECOVER';
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_ENTRY =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_ENTRY';
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_SUCCESS';
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILED =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_FAILED';
export const SIGN_IN_WITH_EMAIL_AND_PASSWORD_RECOVER =
  'SIGN_IN_WITH_EMAIL_AND_PASSWORD_RECOVER';

export const AUTH_WITH_PHONE_NUMBER_ENTRY = 'AUTH_WITH_PHONE_NUMBER_ENTRY';
export const AUTH_WITH_PHONE_NUMBER_SUCCESS = 'AUTH_WITH_PHONE_NUMBER_SUCCESS';
export const AUTH_WITH_PHONE_NUMBER_FAILED = 'AUTH_WITH_PHONE_NUMBER_FAILED';
export const AUTH_WITH_PHONE_NUMBER_RECOVER = 'AUTH_WITH_PHONE_NUMBER_RECOVER';
